language: java
sudo: true
jdk:
- oraclejdk8
install: true
script: ./gradlew -S -Pskip.signing build artifactoryPublish bintrayUpload -PbintrayUsername=$BINTRAY_USER
  -PbintrayApiKey=$BINTRAY_KEY
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: EMTweiQ6YiTqsEfUcYIYdnMW/NMBmOcIKH5w06JPu0gf5kXV+IoLkjjD1M9ygD1LG17pOA34mx6uK4LaoXpD3f5608gNKzYg5vSZF9A2U2hATHZUIsz0fw/gU8m29M5pPSdxAMs3Pu3QXRvooszNWPkAVCOduOZVe9rA1hJkyOB4cHGB4sJfyQLe6nN5VVczyz/fX+OkjqVRuq3h32vF2DoNWsVw85XSsnOSSwZqWvweF+YOevTmSmFd24kfCGEhoWUu9Fl+TU63J3gyyVQIC3tn8bJ/+g0PbdARXH7UUx38M9P4GQ6KDPwBHkQoG1SdHUUbJA1YJ9ydm6VIpqCX++uGJ7rTuEMuFy7pD9KKTdwUBNc9TObCygb4v+ddb8YnMMYoE8PEasTvt2rUOkc4mLRbFj3rcYKlgJKgLlJnB/y4IGsxaKka692JHHdp4Ch05p2yFBVxSYtmRbZikh2U1pgR5Y6OUQOHSuIEbCVyMdCM1p07rtyUuL5qUlGYy95TXYlE5D3dr7vwelQFDePsrTyi7l7BxWh7USKSBisjhkL3njFulbK8wvFQ+NIBsBP751BAy+V/yDg+sJv/EcbUogb0Oe1E5tR6JJ6o5N6QwecsizBmg/2gvLaGHezVXsPb3wAL3d9od/4/xJFHXHEcAvotwKrKCWn/mTw/j8tIO60=
